export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SHOW_CART: "SHOW_CART",
  ADD_TO_CART: "ADD_TO_CART",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SHOW_PRODUCTS_IN_CART: "SHOW_PRODUCTS_IN_CART",
  HIDE_PRODUCTS_IN_CART: "HIDE_PRODUCTS_IN_CART",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
};
